name: Relato de Bug
description: Informe um erro para nos ajudar a melhorar o Sortudo?
title: "[BUG]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por relatar o problema! Por favor, preencha as informações abaixo.
  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Uma descrição clara e concisa do que é o bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Como Reproduzir
      description: Passos para reproduzir o comportamento.
      placeholder: |
        1. Vá para '...'
        2. Clique em '....'
        3. Role para baixo até '....'
        4. Veja o erro
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: Uma descrição clara do que você esperava que acontecesse.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Capturas de Tela
      description: Se aplicável, adicione capturas de tela para ajudar a explicar o problema.
  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: Navegador, SO, Versão do Node, etc.
